![logo_ironhack_blue 7](https://user-images.githubusercontent.com/23629340/40541063-a07a0a8a-601a-11e8-91b5-2f13e4e6b441.png)

# Lab | Web Scraping Single Page

#### Business goal:

- Check the `case_study_gnod.md` file.
- Make sure you've understood the big picture of your project:

  - the goal of the company (`Gnod`),
  - their current product (`Gnoosic`),
  - their strategy, and
  - how your project fits into this context.

  Re-read the business case and the e-mail from the CTO, take a look at the flowchart and create an initial Trello board with the tasks you think you'll have to accomplish.

#### Instructions - Scraping popular songs

Your product will take a song as an input from the user and will output another song (the recommendation). In most cases, the recommended song will have to be similar to the inputted song, but the CTO thinks that if the song is on the top charts at the moment, the user will enjoy more a recommendation of a song that's also popular at the moment.

You have find data on the internet about currently popular songs. Billboard maintains a weekly Top 100 of "hot" songs here: [https://www.billboard.com/charts/hot-100](https://www.billboard.com/charts/hot-100).

It's a good place to start! Scrape the current top 100 songs and their respective artists, and put the information into a pandas dataframe.

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import re

In [2]:
#Asignamos el URL como variable
URL='https://www.billboard.com/charts/hot-100'

In [3]:
#Llamamos al URL para el acceso.
response = requests.get(URL)

In [4]:
soup = BeautifulSoup(response.content, "html.parser")

In [5]:
canciones = []
for i in range (100):
   canciones.append(soup.select('li h3')[i].get_text(strip=True).replace('\t', ''))

In [6]:
canciones

['Last Night',
 'Kill Bill',
 'Flowers',
 'Ella Baila Sola',
 'Un x100to',
 'Calm Down',
 "Creepin'",
 'Die For You',
 "Boy's A Liar, Pt. 2",
 'Anti-Hero',
 'La Bebe',
 'Search & Rescue',
 'Favorite Song',
 'Fast Car',
 'Sure Thing',
 'Players',
 'Rock And A Hard Place',
 'Double Fantasy',
 'You Proof',
 'As It Was',
 'Chemical',
 'One Thing At A Time',
 "Thinkin' Bout Me",
 'Thought You Should Know',
 "I'm Good (Blue)",
 'Something In The Orange',
 'Thank God',
 'Por Las Noches',
 'Princess Diana',
 'Escapism',
 'Under The Influence',
 "Dancin' In The Country",
 'PRC',
 'Slut Me Out',
 'Lavender Haze',
 'Handle On You',
 'Unholy',
 'Snooze',
 'Just Wanna Rock',
 'AMG',
 'Cupid',
 'Superhero (Heroes & Villains)',
 'TQG',
 'Wait In The Truck',
 'Eyes Closed',
 'Spin Bout U',
 'Daylight',
 'Rich Flex',
 'Love You Anyway',
 'Bebe Dame',
 'Wild As Her',
 'See You Again',
 'Tennessee Orange',
 'Next Thing You Know',
 'Alone',
 'Chanel',
 'El Azul',
 'Haegeum',
 'Low Down',
 'Need A Favor',
 'Bloody Mary',
 'Peaches',
 'Nonsense',
 "Ain't That Some",
 'Fight The Feeling',
 'Red Ruby Da Sleeze',
 'Beso',
 'Ch y La Pizza',
 'Cowgirls',
 'I Wrote The Book',
 'El Gordo Trae El Mando',
 'Gold',
 'Man Made A Bar',
 'Everything I Love',
 'Karma',
 'ICU',
 'Que Vuelvas',
 'Trance',
 'Yandel 150',
 'Igualito A Mi Apa',
 'In Ha Mood',
 'Fragil',
 'Human',
 'Painting Pictures',
 'Never Felt So Alone',
 'Dawns',
 'Ceilings',
 'Memory Lane',
 'Di Que Si',
 'Strike (Holster)',
 'Happy',
 'Forever',
 'Moonlight',
 'Sunrise',
 "You Didn't",
 'It Matters To Her',
 'Like Crazy',
 'All Of The Girls You Loved Before',
 '5 Leaf Clover',
 'Big Truck']

In [7]:
rolas = np.array(canciones)
rolas2 = pd.DataFrame(rolas)
rolas2 = rolas2.rename(columns = {0: 'Canción'})

In [8]:
rolas2

                              Canción
0                          Last Night
1                           Kill Bill
2                             Flowers
3                     Ella Baila Sola
4                           Un x100to
..                                ...
95                  It Matters To Her
96                         Like Crazy
97  All Of The Girls You Loved Before
98                      5 Leaf Clover
99                          Big Truck

[100 rows x 1 columns]

In [9]:
artistas = []
for i in range (100):
   artistas.append(soup.select('.c-label.a-no-trucate')[i].get_text(strip=True).replace('\t',''))


   #canciones.append(soup.select('li h3')[i].get_text(strip=True).replace('\t', ''))

In [10]:
artistas

['Morgan Wallen',
 'SZA',
 'Miley Cyrus',
 'Eslabon Armado X Peso Pluma',
 'Grupo Frontera X Bad Bunny',
 'Rema & Selena Gomez',
 'Metro Boomin, The Weeknd & 21 Savage',
 'The Weeknd & Ariana Grande',
 'PinkPantheress & Ice Spice',
 'Taylor Swift',
 'Yng Lvcas x Peso Pluma',
 'Drake',
 'Toosii',
 'Luke Combs',
 'Miguel',
 'Coi Leray',
 'Bailey Zimmerman',
 'The Weeknd Featuring Future',
 'Morgan Wallen',
 'Harry Styles',
 'Post Malone',
 'Morgan Wallen',
 'Morgan Wallen',
 'Morgan Wallen',
 'David Guetta & Bebe Rexha',
 'Zach Bryan',
 'Kane Brown With Katelyn Brown',
 'Peso Pluma',
 'Ice Spice & Nicki Minaj',
 'RAYE Featuring 070 Shake',
 'Chris Brown',
 'Tyler Hubbard',
 'Peso Pluma X Natanael Cano',
 'NLE Choppa',
 'Taylor Swift',
 'Parker McCollum',
 'Sam Smith & Kim Petras',
 'SZA',
 'Lil Uzi Vert',
 'Gabito Ballesteros, Peso Pluma & Natanael Cano',
 'Fifty Fifty',
 'Metro Boomin, Future & Chris Brown',
 'Karol G x Shakira',
 'HARDY Featuring Lainey Wilson',
 'Ed Sheeran',
 'Drake & 21 Savage',
 'David Kushner',
 'Drake & 21 Savage',
 'Luke Combs',
 'Fuerza Regida X Grupo Frontera',
 'Corey Kent',
 'Tyler, The Creator Featuring Kali Uchis',
 'Megan Moroney',
 'Jordan Davis',
 'Kim Petras Featuring Nicki Minaj',
 'Becky G & Peso Pluma',
 'Junior H x Peso Pluma',
 'Agust D',
 'Lil Baby',
 'Jelly Roll',
 'Lady Gaga',
 'Jack Black',
 'Sabrina Carpenter',
 'Morgan Wallen',
 'Rod Wave',
 'Nicki Minaj',
 'Rosalia & Rauw Alejandro',
 'Fuerza Regida X Natanael Cano',
 'Morgan Wallen Featuring ERNEST',
 'Morgan Wallen',
 'Chino Pacas',
 'Dierks Bentley',
 'Morgan Wallen Featuring Eric Church',
 'Morgan Wallen',
 'Taylor Swift',
 'Coco Jones',
 'Carin Leon X Grupo Frontera',
 'Metro Boomin, Travis Scott & Young Thug',
 'Yandel & Feid',
 'Fuerza Regida & Peso Pluma',
 'Ice Spice',
 'Yahritza y Su Esencia x Grupo Frontera',
 'Cody Johnson',
 'Superstar Pride',
 'Labrinth',
 'Zach Bryan Featuring Maggie Rogers',
 'Lizzy McAlpine',
 'Old Dominion',
 'Grupo Marca Registrada X Grupo Frontera',
 'Lil Yachty',
 'NF',
 'Lil Baby Featuring Fridayy',
 'Kali Uchis',
 'Morgan Wallen',
 'Brett Young',
 'Scotty McCreery',
 'Jimin',
 'Taylor Swift',
 'Luke Combs',
 'YoungBoy Never Broke Again']

In [11]:
artistas1 = np.array(canciones)
artistas2 = pd.DataFrame(artistas)
artistas2 = artistas2.rename(columns = {0: 'Artistas'})

In [12]:
artistas2

                       Artistas
0                 Morgan Wallen
1                           SZA
2                   Miley Cyrus
3   Eslabon Armado X Peso Pluma
4    Grupo Frontera X Bad Bunny
..                          ...
95              Scotty McCreery
96                        Jimin
97                 Taylor Swift
98                   Luke Combs
99   YoungBoy Never Broke Again

[100 rows x 1 columns]

In [13]:
billboard = pd.concat([rolas2,artistas2],axis=1)
#billboard = billboard.rename(columns = {0: 'Canción', 0: 'Artista'})

billboard

                              Canción                     Artistas
0                          Last Night                Morgan Wallen
1                           Kill Bill                          SZA
2                             Flowers                  Miley Cyrus
3                     Ella Baila Sola  Eslabon Armado X Peso Pluma
4                           Un x100to   Grupo Frontera X Bad Bunny
..                                ...                          ...
95                  It Matters To Her              Scotty McCreery
96                         Like Crazy                        Jimin
97  All Of The Girls You Loved Before                 Taylor Swift
98                      5 Leaf Clover                   Luke Combs
99                          Big Truck   YoungBoy Never Broke Again

[100 rows x 2 columns]